### ISSUE TITLE
Provisioner stays active if the worker fails.

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tink#106]
When the datacenter didn’t have hosts for both provisioner and worker, it spent over 3 minutes creating the provisioner before failing; the worker wasn’t started. After it failed, the provisioner was still there until I ran terraform apply with the new datacenter details. If the worker fails, it would be nice for the provisioner to shut down.

**Comment by parauliya** [comment]
@thomcrowe , I don't agree with your point of failing provisioner if the worker fails since, provisioner is the one who is responsible of creating workflows for different workers. In case of multiple workers there can be multiple worklfows for different workers. Therefore if one worker fails we can't fail provisioner because it has workflows for other workers which still needs to be run.
 
Please let me know if I understood your concern correctly and close the issue else provide a bit of explaination of what you are trying to say.

**Comment by grahamc** [comment]
Is this when using the terraform-based quick start? In that case, I think it would be reasonable to set the expectation that users are familiar with Terraform ahead of time. Given that expectation, it is reasonable that a user would understand they needed to destroy the provisioner.

I can imagine a case where a provision fails for an unrelated reason. If that unrelated reason is retryable, tearing down the other machine would add a significant slowdown to the process of getting started.

**Comment by thomcrowe** [comment]
Makes sense.

Thanks y'all!
