### ISSUE TITLE
Worker PXE-boots after workflow is done

### ISSUE THREAD

**Issue by iaguis** [tinkerbell/tink#116]
Currently, when a workflow is done and the user reboots, workers PXE-boot again to OSIE unless you manually set boot to disk. I tested this installing Flatcar on Packet following the [tinkerbell.org tutorial](https://tinkerbell.org/setup/).

It'd be great if there's a way to tell the worker to not PXE-boot after a workflow is done.

**Comment by alexellis** [comment]
👍 - at the least, it would make a good addition to the notes to describe how the system currently works. I think it might be a confusing experience for new users otherwise.

Short-term: note in docs?
Medium-term: CLI example for Packet's IPMI interface to change boot order?
Longer-term: feature?

**Comment by Cbkhare** [comment]
I tried to replicate this issue. 

With the implementation of https://github.com/tinkerbell/boots/issues/35, until there is no active workflow, PXE-boot won't happen. On replicating I found, it gets blocked before PXE step. I also tested it with worker and workflow to install Ubuntu OS. On reboot, ubuntu is brought and pxe-boot doesn't happen.

**Comment by gianarb** [comment]
@DailyAlice wrote documentation for the workflow execution that I hope will clarify a bit this behavior
https://github.com/tinkerbell/tinkerbell.org/pull/110/files

Tinkerbell does not do any magic action. The worker has to be configured to start from disk otherwise if an operating system is not found it will follow the boot chain going to network boot (PXE).

If your behavior looks not in line with this and it sounds like a bug please open a new issue with a workflow that we can test.

Thanks a lot
