### ISSUE TITLE
Provide clean up script to clean up the failed installation

### ISSUE THREAD

**Issue by wangxin311** [tinkerbell/tink#118]
Currently, there is no clean_up.sh script to clean up the environment in case of the setup.sh is failed, if the last setup.sh is failed for some reason, we can not run the setup.sh again if some configuration already there like interface configuration, we have to manually clean it up before restart setup.sh again. It would be nice to provide a clean_up.sh script to clean up the environment for reinstall, thanks

**Comment by gianarb** [comment]
Hello

We changed the setup.sh script few weeks ago and it can now run multiple times safely. Cleanup for reinstallation should not be a problem anymore. 

I am gonna close it for now, if you get an error that requires a cleanup let us know with a dedicated PR reporting the error because there is a continuously ongoing effort to make the setup script idempotent.

Thanks a lot!
