### ISSUE TITLE
tink cli - `--file` and `--path` flags not opening and reading files

### ISSUE THREAD

**Issue by DailyAlice** [tinkerbell/tink#209]
According to the current docs using `tink hardware push` should take a `--file` flag with a filename. Instead it just hangs.
```
docker exec -i deploy_tink-cli_1 tink hardware push --file hardware-data.json
> hangs
^C
```
This works though:
```
docker exec -i deploy_tink-cli_1 tink hardware push < ./hardware-data.json
>
2020/07/06 17:37:12 Hardware data pushed successfully
```

Similarly, `tink template create` should take a `--path` flag with a filename. It also hangs.
```
docker exec -i deploy_tink-cli_1 tink template create --name hello-world --path hello-world.yml
> hangs
^C
```
This works though:
```
docker exec -i deploy_tink-cli_1 tink template create --name hello-world < ./hello-world.yml
>
Created Template:  aeedc9e2-6c1a-419f-976c-60f15803796f
```

It is my understanding that both are supposed to work. Working on the documentation to reflect what the intended and actual behavior is.

I have only tested with the Vagrant setup. I don't not know if both commands work outside of it. It would be nice to confirm with someone running running the `tink-cli` somewhere else, or outside a container.

**Comment by Cbkhare** [comment]
hey @DailyAlice, 

I looked into the issue. The problem you are facing is due to `docker exec`. Below points highlights the RCA. 

1) Problem is _**not**_ with tink-cli. It works completely fine. 
    I verified it by executing the tink commands from inside the tink-cli container using `--file` and `--path` params. 
    `docker exec -it deploy_tink-cli_1 sh` 
    `/ # tink hardware push --file hd.json `
   ` 2020/07/14 06:52:34 Hardware data pushed successfully`
    
    `/ # tink template create --name test-1 --path tmp.yml `
    `Created Template:  052fff2d-5375-433e-a501-fddfaaf39628`

2) `docker exec` is used to execute command on the container from the host. But it also depends on the way we use it. In your case you are using `i` parameter which is interactive mode and keeps the `stdin` open. This is the reason you are seeing the cli getting hanged. For more ref: https://docs.docker.com/engine/reference/commandline/exec/#options

3) since you are executing the command from the host (i.e outside the container) the file which you redirect to using `--file` or path using `--path`, then the file should be in the given location. You can verify it by executing below command but with `t` (instead of `i`) in the docker exec params. (before executing below command, i had placed hd.json in the root location of tink-cli container). 
    `docker exec -t deploy_tink-cli_1 tink hardware push --file hd.json `
    `2020/07/14 07:07:04 Hardware data pushed successfully`


So as of now, with limitation in `dockre exec` we may have to stick to `<` to push the file data if command is executed from the host, but this issue definitely demands a way to execute tink-cli from the host without using `docker-exec` and also could be a good feature to have in the product.

I have added this part as a requirement in the proposals, https://github.com/tinkerbell/proposals/pull/1/files#diff-0f09a6f3d8ecf41c5dcd6e2252c5137b. It would be great if you can review the PR.

**Comment by DailyAlice** [comment]
Thanks for looking into it @Cbkhare!

This clears up a lot for me, and I think for right now, I can definitely clarify in the docs when to use the flags vs when to use `<` and why.

I don't really have approve or write access for the linked proposal repo, but added a comment in support.

**Comment by gauravgahlot** [comment]
@DailyAlice can we close this issue?

**Comment by DailyAlice** [comment]
Sure! When I get around to tackling the nitty-gritty details of adding this to the CLI docs, I'll track it in a new/separate issue.
