### ISSUE TITLE
Support provisioning Intel NUC

### ISSUE THREAD

**Issue by zsmith928** [tinkerbell/tink#25]
We should test and support Intel NUC machines in BIOS and UEFI mode, such as the [Nuc Kit](https://www.intel.com/content/www/us/en/products/boards-kits/nuc/kits/nuc7cjyh.html)

**Comment by thebsdbox** [comment]
This has been successfully tested on Gigabyte Brix, in order to prove out the Tinkerbell workflow. Any hardware (including virtual) that can PXE boot should be supported to start a workflow through tinkerbell (and iPXE). Once consideration for NUCs/Brix and other small hardware is ensuring that enough memory exists in order to boot OSIE and workflow containers in memory.

**Comment by gianarb** [comment]
I am using Tinkerbell on my NUCs successfully and I wrote about it here.

https://metal.equinix.com/blog/building-an-ephemeral-homelab/

I think we can close this issue for now. @zsmith928 if you have a different goal in mind let me know
