### ISSUE TITLE
Docker-compose fails to build services

### ISSUE THREAD

**Issue by charlottemach** [tinkerbell/tink#320]
## Expected Behaviour
When running `docker-compose up -d` on a fresh install, the images should be built and started.

## Current Behaviour

Following error occurs:
```
~/tink/deploy# docker-compose up -d
Building tink-server-migration
Step 1/6 : FROM alpine:3.11
 ---> f70734b6a266
Step 2/6 : ENTRYPOINT ["tink-server"]
 ---> Using cache
 ---> 7941af280a7a
Step 3/6 : EXPOSE 42113
 ---> Using cache
 ---> 78ee394452fd
Step 4/6 : EXPOSE 42114
 ---> Using cache
 ---> fff67a9c9dc0
Step 5/6 : RUN apk add --update ca-certificates &&     apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing cfssl
 ---> Using cache
 ---> 3083ba50c26d
Step 6/6 : COPY tink-server /bin/
ERROR: Service 'tink-server-migration' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder908318258/tink-server: no such file or directory
```

## Possible Solution

1. Add how-to build services locally to setup guide (as /cmd/tink-server/tink-server etc are not existing after a fresh setup and are in the .gitignore)
or 
2. Change the docker-compose.yml file back (think this change https://github.com/tinkerbell/tink/commit/9483014c617b8034b54d46fec65bce9bfa5364bd#diff-e3b592b8cfcc2838d7cb2a5d2cdbb2ef causes it).

## Steps to Reproduce (for bugs)

1. Following these steps https://docs.tinkerbell.org/setup/packet-terraform/#setting-up-the-provisioner

## Your Environment

* Debian 8 with slightly adapted setup.sh

**Comment by gianarb** [comment]
Hello @charlottemach !

I know what it is, I am trying to figure out a good way to develop locally but there is so much going on that I get lost time to time.

So this issue is related to #312 somehow. We build the binaries externally from Docker but we use docker-compose to get a fresh image. Can you try a thing for me.

Can you revert to `master` (the version that it does not work for you) and from your local env can you run `GOOS=linux make all`, and after that can you start `docker-compose up -d` as usual?

Thanks, just to help me validate what I am thinking

**Comment by charlottemach** [comment]
I hadn't noticed the setup instructions changed to the sandbox repo, thanks @gianarb!
I don't have go on that machine, I'll just switch to the other repo.
