### ISSUE TITLE
One workflow at a time?

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#399]
tink allows multiple workflows to be allocated to a worker at a time. There's no technical reason why this isn't fine, but it seems to me that its probably a user mistake? Every time I've come across this I would have rather that tink let me know that a workflow was already in progress, which I would then have terminated.

If we decide not to treat it as an error should we instead give feedback that N workflows are queued up/active?

**Comment by gianarb** [comment]
How does it work today? if a second (B) workflow is created when the first (A) is ongoing the worker will end (A) and work pick up (B) or they will work side by side?

I suppose one at a time. If so your question is: Do we want to return an error in this scenario preventing (B) to be created if the worker is busy doing something else?

I think queuing can be comfortable but it also adds more complexity, if (A) ends with a reboot and the hardware never boots via network again the workflow will stay in a pending state, and maybe it will be a cause of confusion later on after weeks when for some reason the hardware netboot again to Osie and the workflows get executed.

I don't have an opinion yet that's why I am trying to build some more context around this

**Comment by mmlb** [comment]
> How does it work today? if a second (B) workflow is created when the first (A) is ongoing the worker will end (A) and work pick up (B) or they will work side by side?

Nope they work as you'd expect. First (A) continues until it's done, and then (B) starts and does its thing.

> 
> I suppose one at a time. If so your question is: Do we want to return an error in this scenario preventing (B) to be created if the worker is busy doing something else?
> 
> I think queuing can be comfortable but it also adds more complexity, if (A) ends with a reboot and the hardware never boots via network again the workflow will stay in a pending state, and maybe it will be a cause of confusion later on after weeks when for some reason the hardware netboot again to Osie and the workflows get executed.

That workflow *should* timeout before then :D. But yes I think its really only open for confusion. Either the worker is available or its busy with a workflow for now please try again.

> 
> I don't have an opinion yet that's why I am trying to build some more context around this

**Comment by gianarb** [comment]
> But yes I think its really only open for confusion

I like to avoid that. So yep, I think we can return some error that the client can interpret as "resource busy.. retry..."

**Comment by chrisdoherty4** [comment]
There have been substantial changes since this issue was raised. Its still somewhat relevant but I think we can address the current concerns as a separate issue.
