### ISSUE TITLE
tink-worker should not use status 'bars' when downloading containers

### ISSUE THREAD

**Issue by splaspood** [tinkerbell/tink#451]
As tink-worker downloads action container images it outputs a continually updated status/percentage bar as it first downloads, then extracts, each layer.    This leads to a lot of useless log entries.

## Expected Behaviour
Since the STDIO from tink-worker is generally meant to be ingested into a centralized logging setup wherein automated systems, primarily, will be 'monitoring' the logs, this output leads to a ton of arguably useless logging.

## Possible Solution
tink-worker should simply log 'Downloaded layer id xyz' 'Extracted layer id xyz' rather than a continually scrolling bar-graph style status bar.

**Comment by gianarb** [comment]
I am gonna ping @Cbkhare and @invidian for visibility.

@splaspood as you can see reading this ongoing conversation https://github.com/tinkerbell/tink/pull/450#discussion_r589447640 other people kind of like to have visibility on what is going on.

BUT

I agree a progress bar as it is today is kind of unmanageable at scale when you aggregate 100 tink-workers doing things at the same time. 

The solution is probably not to log twice, because as I read from @invidian he kind of likes the idea to have more feedback when an image talks forever to pull. (I think in a proper data center where images are proxies in a private network you know how much it should take more or less.. so I am not that concerned, but probably for home labs is different.

---

This is my proposal, we remove the progress bar and we open an issue to figure out a better way, maybe we can use Prometheus metrics, or we can log progress without printing a bar and with a better timing strategy.

**Comment by invidian** [comment]
I'm fine with removing the progress bar if it's a deliberate decision, it's really only useful in debugging :+1: My point in #450 was mainly to not remove the functionality as a side effect of a bug fix.

**Comment by gianarb** [comment]
As I wrote there I agree with you @invidian and thank you for catching it!!

**Comment by Cbkhare** [comment]
Hey @invidian ,

I think we all agree here then may be we can invalidate this comment Check this comment on 450 https://github.com/tinkerbell/tink/pull/450#discussion_r589447640

And reference 451 there.

**Comment by markyjackson-taulia** [comment]
@gianarb @invidian @Cbkhare @splaspood would it make sense to add a flag that would disable this functionality (progress bar only), leaving the default behavior with the progress bar?

**Comment by gianarb** [comment]
Hey Marky, personally I think that's the wrong solution. I think progress
bars as they get visualized by default do not fit this use case. There is
already a natural and expected feature flag when it comes to logging called
log level.
An acceptable solution for me is to figure out how we can inject a
different logger replacing the progress bar with something different, maybe
that uses log level debug so only in that circumstances it will show up

**Comment by markyjackson-taulia** [comment]
My concern with trying to replace the progress bar with something different will either not catch enough use cases or too many edge cases, and thus creating a whole new set of problems.
Simply allowing either the ability to turn this progress bar feature on or off via a flag seems more the optimal path imo.
But we can also just leave it and not worry too.

**Comment by gianarb** [comment]
Did you look at how the logging strategy works for Docker pull and what we
can do with it? I don't have experience around it. Let's avoid an
additional feature flags for logging that is not a log level if we can.
Otherwise we can mask any little thing with a feature flag and it can
quickly become very confusing

**Comment by invidian** [comment]
If we put this under a log level flag, how can this be configured from user level? As part of workflow configuration? In hardware profile?

**Comment by gianarb** [comment]
We do not have a way to control how tink-worker starts, or at least it is
left to the user or installation environment implementation.
For example, if you use OSIE it downloads a bash script from the Nginx
server that defines how tink-worker starts. Hook does not have any
capability like that, it will require to build your own installation
environment.
At least that's how it is today

**Comment by chrisdoherty4** [comment]
We're re-writing the Tink worker and will take this into consideration as part of the re-write.
