### ISSUE TITLE
setup support for CentOS 8

### ISSUE THREAD

**Issue by nathangoulding** [tinkerbell/tink#66]
Issue summary is pretty descriptive - adding support for setting this up on CentOS 8 in addition to CentOS 7.

As part of this, we should consider stopping the script if it's on an unsupported OS.

**Comment by DavidZisky** [comment]
BIt tricky. The problem is RedHat blocked installation of containerd.io > 1.2.0-3.el7, which is a dependency of docker. Therefore, running a `dnf install docker-ce`, won't work :( it's possible to workaround that by installing specific (older) version of docker but even then DNS resolution (in docker) won't work unless firewalld is disabled... so there are workarounds to make it work but no "nice" solution
