### ISSUE TITLE
Cut release tags from tink

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#74]
Git enables releases to be made, these are shown in the GitHub Releases page.

<img width="1029" alt="Screenshot 2020-04-23 at 10 53 19" src="https://user-images.githubusercontent.com/6358735/80085802-a926ed80-8550-11ea-8199-720b2d5a0494.png">

Tink currently has none, however I would suggest that the project starts to use them, even if they are RC tags or very early alpha tags.

For instance:

0.1.0
0.1.1

and so forth...

These tags can be checked out, show progress being made to internal and external stakeholders, and allow users to reason about "versions"

Example: https://github.com/alexellis/arkade/releases

If you install the Derek app on this repo, it will generate notes with all the PRs and commits pushed automatically.

<img width="1011" alt="Screenshot 2020-04-23 at 10 53 04" src="https://user-images.githubusercontent.com/6358735/80085784-a0361c00-8550-11ea-9a5d-fe70142bc06d.png">

**Comment by alexellis** [comment]
I would also add that you do not need to push Docker images or cut binaries for each release, although that would be a nice addition.

**Comment by thebsdbox** [comment]
https://github.com/tinkerbell/tink/issues/94 The version subcommand will also become part of the same piece of work.

**Comment by gianarb** [comment]
We decided to release the only sandbox for now because this is a too fast-moving project at this stage and the responsibility is not totally split. It means that it is very hard to tag all the projects by themself. 

I will close this issue for now and have a look at https://github.com/tinkerbell/sandbox/releases if you want a pinned version and binaries as well!
